language: ruby
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - rbx
gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  allow_failures:
    - rvm: rbx

addons:
  postgresql: "9.2"

before_script:
  - cp spec/database.yml.travis spec/database.yml
  - psql -U postgres -c 'create database surus_test;'
  - psql -U postgres -f spec/database_structure.sql surus_test

script:
  - bundle exec rake spec
  - bundle exec rubocop
